# Generated by Django 6.0.4 on 2026-04-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="bio",
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
    ]
